# Build hello world

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: CmdLine@2
  inputs:
    script: |
      ls
      echo "Hello world"
- script: dotnet build dotnet/HelloWorld/*.sln --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
